In [1]:
import numpy as np

In [4]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(3)

array([1., 1., 1.])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

# identity matrix

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(5)

array([0.60005131, 0.25543334, 0.45710702, 0.60284709, 0.89090193])

In [14]:
np.random.rand(5,5)

array([[0.98553407, 0.99391725, 0.02007281, 0.06713663, 0.81296291],
       [0.43323167, 0.88753374, 0.84320362, 0.90132951, 0.27987875],
       [0.29116658, 0.19949409, 0.36675039, 0.01752194, 0.64040393],
       [0.63474834, 0.70954318, 0.46907952, 0.56344327, 0.89977123],
       [0.99228942, 0.59293927, 0.38810713, 0.29261955, 0.31087504]])

In [15]:
np.random.randn(5,5)

array([[-0.44788358, -0.5535102 , -0.44674534,  1.24717411, -0.67852804],
       [-0.02520805,  0.07765345,  1.14047926, -3.83639916,  0.4828415 ],
       [-1.1206476 , -1.2791548 , -0.96462945,  0.36855797, -0.72937525],
       [ 0.63812799, -0.36184003,  0.34845315,  0.25678176,  0.57811054],
       [ 0.85896834, -1.69222866, -0.91703745, -0.03458005,  0.10823494]])

In [16]:
np.random.randn(5)

array([-1.37783005,  0.16163521, -1.35619613, -0.17176636, -0.21639334])

In [17]:
np.random.randint(1,100)

23

In [18]:
np.random.randint(1,100,10)

array([74, 19, 60, 39, 82, 13, 34,  4, 68, 47])

In [19]:
arr = np.arange(25)

In [20]:
ranarr = np.random.randint(0,50,10)

In [21]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
ranarr

array([19, 43, 13, 23, 17, 47, 16, 45, 46, 20])

In [24]:
ranarr.max()

47

In [25]:
ranarr.min()

13

In [26]:
ranarr.argmax()

5

In [27]:
ranarr.argmin()

2